### ISSUE TITLE
 "private_key_path" has not been declared.

### ISSUE THREAD

**Issue by bhushanarora2006** [oracle-quickstart/oci-arch-cassandra#2]
While deploying this on OCI Console as stacks, getting following error. It's not prompting to provide the path of private key in console display but it looks deployment is expecting the private key path. Can we enable the display to provide the path from OCI console only:

Error: Reference to undeclared input variable
  on provider.tf line 18, in provider "oci" 
  18:   private_key_path     = var.private_key_path
An input variable with the name "private_key_path" has not been declared.
This variable can be declared with a variable "private_key_path" {} block.

**Comment by lfeldman** [comment]
Please continue to use this repository: https://github.com/oracle-devrel/terraform-oci-arch-cassandra.
